---
include:
  - board: nice_nano_v2
    shield: temper_left
    artifact-name: "LEFT Temper Wireless NNv2"
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: temper_right
    artifact-name: "RIGHT Temper Wireless NNv2"
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: "RESET Temper Wireless NNv2"